### Day 3

In [4]:
with open('AoC4a.txt') as fp:
    list1 = fp.read()

In [5]:
strings1 = list1.split(',')

In [6]:
newlist1 = []
for strings in strings1:
    if strings[0] == 'R':
        newlist1.append('1')
    if strings[0] == 'L':
        newlist1.append('2')  
    if strings[0] == 'U':
        newlist1.append('3')    
    if strings[0] == 'D':
        newlist1.append('4')    
    newlist1.append(strings[1:])

In [7]:
intlist1 = []
for strings in newlist1:
    strings = int(strings)
    intlist1.append(strings)
    
print(type(intlist1[7]))

<class 'int'>


In [8]:
matrix = 28000

In [9]:
center = int(matrix / 2)

#### 1 --> Right
#### 2 --> Left
#### 3 --> Up
#### 4 --> Down

In [10]:
import numpy as np
zeros = np.zeros( (matrix, matrix) )
print(zeros)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [11]:
def AOC3(intlist1, zeros):
    way = 0
    col = center
    row = center
    
    while way < len(intlist1):
        if intlist1[way] == 1:
            for step in range(intlist1[way+1]):
                col = (col + 1)
                zeros[row][col] = 1
        if intlist1[way] == 2:
            for step in range(intlist1[way+1]):
                col = (col - 1)
                zeros[row][col] = 1        
        if intlist1[way] == 3:
            for step in range(intlist1[way+1]):
                row = (row - 1)
                zeros[row][col] = 1
        if intlist1[way] == 4:
            for step in range(intlist1[way+1]):
                row = (row + 1)
                zeros[row][col] = 1
        way = way + 2

In [12]:
AOC3(intlist1, zeros)

In [13]:
with open('AoC4b.txt') as fp:
    list2 = fp.read()

In [14]:
strings2 = list2.split(',')

In [15]:
newlist2 = []
for strings in strings2:
    if strings[0] == 'R':
        newlist2.append('1')
    if strings[0] == 'L':
        newlist2.append('2')  
    if strings[0] == 'U':
        newlist2.append('3')    
    if strings[0] == 'D':
        newlist2.append('4')    
    newlist2.append(strings[1:])

In [16]:
intlist2 = []
for strings in newlist2:
    strings = int(strings)
    intlist2.append(strings)
    
print(type(intlist2[7]))

<class 'int'>


In [17]:
def AOC3_2(intlist2, zeros):
    way = 0
    col = center
    row = center
    
    while way < len(intlist2):
        if intlist2[way] == 1:
            for step in range(intlist2[way+1]):
                col = (col + 1)
                if zeros[row][col] == 1:
                    zeros[row][col] = 2
        if intlist2[way] == 2:
            for step in range(intlist2[way+1]):
                col = (col - 1)
                if zeros[row][col] == 1:
                    zeros[row][col] = 2     
        if intlist2[way] == 3:
            for step in range(intlist2[way+1]):
                row = (row - 1)
                if zeros[row][col] == 1:
                    zeros[row][col] = 2
        if intlist2[way] == 4:
            for step in range(intlist2[way+1]):
                row = (row + 1)
                if zeros[row][col] == 1:
                    zeros[row][col] = 2
        way = way + 2

In [22]:
AOC3_2(intlist2, zeros)

IndexError: index 28000 is out of bounds for axis 0 with size 28000

In [23]:
def aoc3dif2(zeros):
    result = np.where(zeros == 2)
    print(result)
    listOfCoordinates= list(zip(result[0], result[1]))
    print(" lenght of listOfCoordinates = ", (len(listOfCoordinates)))
    coords = []
    for tuples in listOfCoordinates:
        coords.append(list(tuples))
    diff = []
    for lists in coords:
        dif = abs(lists[0] - center) + abs(lists[1] - center)
        diff.append(dif)
    print(len(diff))
    solution = min(diff)
    print(diff[:10])
    print(coords)
    print(solution)
    return


In [24]:
aoc3dif2(zeros)

(array([10778, 10778, 10778, 10837, 11095, 11095, 11096, 11096, 11143,
       11335, 11335, 11404, 11644, 11855, 12251, 12299, 12350, 12350,
       12593, 12778, 13064, 13127, 13127, 13232, 13232, 13425, 13507,
       13507, 13507], dtype=int64), array([13917, 13965, 14156, 14382, 14368, 14433, 13990, 14382, 14368,
       13990, 14046, 13818, 13295, 12993, 12993, 13459, 13523, 14024,
       14896, 15327, 15869, 15327, 15488, 15859, 15869, 15327, 15674,
       15859, 15869], dtype=int64))
 lenght of listOfCoordinates =  29
29
[3305, 3257, 3378, 3545, 3273, 3338, 2914, 3286, 3225, 2675]
[[10778, 13917], [10778, 13965], [10778, 14156], [10837, 14382], [11095, 14368], [11095, 14433], [11096, 13990], [11096, 14382], [11143, 14368], [11335, 13990], [11335, 14046], [11404, 13818], [11644, 13295], [11855, 12993], [12251, 12993], [12299, 13459], [12350, 13523], [12350, 14024], [12593, 14896], [12778, 15327], [13064, 15869], [13127, 15327], [13127, 15488], [13232, 15859], [13232, 15869], [13425,

## TEST

In [ ]:
with open('aoc3test.txt') as fp:
    testlist1 = fp.read()

In [ ]:
teststrings1 = testlist1.split(',')

In [ ]:
newtestlist1 = []
for strings in teststrings1:
    if strings[0] == 'R':
        newtestlist1.append('1')
    if strings[0] == 'L':
        newtestlist1.append('2')  
    if strings[0] == 'U':
        newtestlist1.append('3')    
    if strings[0] == 'D':
        newtestlist1.append('4')    
    newtestlist1.append(strings[1:])

In [ ]:
testintlist1 = []
for strings in newtestlist1:
    strings = int(strings)
    testintlist1.append(strings)
    
print(type(testintlist1[7]))
print(testintlist1)

In [ ]:
matrix = 500

In [ ]:
center = int(matrix / 2)

In [ ]:
import numpy as np
testzeros = np.zeros( (matrix, matrix ) )
print(testzeros)

In [ ]:
def testAOC3(testintlist1, testzeros):
    way = 0
    col = center
    row = center
    testzeros[row][col] = -5

    while way < len(testintlist1):
        if testintlist1[way] == 1:
            for step in range(testintlist1[way+1]):
                col = (col + 1)
                testzeros[row][col] = (testzeros[row][col] + 1)
        if testintlist1[way] == 2:
            for step in range(testintlist1[way+1]):
                col = (col - 1)
                testzeros[row][col] = (testzeros[row][col] + 1)
        if testintlist1[way] == 3:
            for step in range(testintlist1[way+1]):
                row = (row - 1)
                testzeros[row][col] = (testzeros[row][col] + 1)
        if testintlist1[way] == 4:
            for step in range(testintlist1[way+1]):
                row = (row + 1)
                testzeros[row][col] = (testzeros[row][col] + 1)
        way = way + 2
    print(testzeros)

In [ ]:
testAOC3(testintlist1, testzeros)

In [ ]:
with open('aoc3test2.txt') as fp:
    testlist2 = fp.read()
print(testlist2)

In [ ]:
teststrings2 = testlist2.split(',')
print(teststrings2)

In [ ]:
newtestlist2 = []
for strings in teststrings2:
    if strings[0] == 'R':
        newtestlist2.append('1')
    if strings[0] == 'L':
        newtestlist2.append('2')  
    if strings[0] == 'U':
        newtestlist2.append('3')    
    if strings[0] == 'D':
        newtestlist2.append('4')    
    newtestlist2.append(strings[1:])
print(newtestlist2)

In [ ]:
testintlist2 = []
for strings in newtestlist2:
    strings = int(strings)
    testintlist2.append(strings)
    
print(type(testintlist2[2]))
print(testintlist2)

In [ ]:
def testAOC3_2(testintlist1, testzeros):
    way = 0
    col = center
    row = center
    testzeros[row][col] = -5

    while way < len(testintlist1):
        if testintlist1[way] == 1:
            for step in range(testintlist1[way+1]):
                col = (col + 1)
                testzeros[row][col] = (testzeros[row][col] + 100)
        if testintlist1[way] == 2:
            for step in range(testintlist1[way+1]):
                col = (col - 1)
                testzeros[row][col] = (testzeros[row][col] + 100)
        if testintlist1[way] == 3:
            for step in range(testintlist1[way+1]):
                row = (row - 1)
                testzeros[row][col] = (testzeros[row][col] + 100)
        if testintlist1[way] == 4:
            for step in range(testintlist1[way+1]):
                row = (row + 1)
                testzeros[row][col] = (testzeros[row][col] + 100)
        way = way + 2
    print(testzeros)

In [ ]:
testAOC3_2(testintlist2, testzeros)

In [ ]:
def aoc3dif2(testzeros):
    result = np.where((testzeros > 100) & ((testzeros % 100) != 0))
    print(result)
    listOfCoordinates= list(zip(result[0], result[1]))
    print(listOfCoordinates)
    coords = []
    for tuples in listOfCoordinates:
        coords.append(list(tuples))
    print(coords)
    diff = []
    for lists in coords:
        dif = abs((lists[0] - center) + abs((lists[1] - center))
        diff.append(dif)
    print(diff)
    solution = min(diff)
    print(solution)
    return

In [ ]:
aoc3dif2(testzeros)

In [ ]:
### listlist = testzeros.tolist()

In [ ]:
### def aoc3dif(listlist):
    winlist = []
    for rows in listlist:
        for elements in rows:
            if elements > 100:
                diff1 = abs((listlist.index(rows) - 200) + (rows.index(elements) - 200))
                winlist.append(diff1)
    print(winlist)
    solution = min(winlist)
    print(solution)

In [ ]:
### aoc3dif(listlist)